project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Extreme Weather Events Analysis in Hurricane Prone States in The USA"
  author:
    - Yelaman Sain (ys3525)
    - Blanca Herreros De Tejada (beh2154)
  repo-url: https://github.com/EDAV-Fall2023-FinalProject-Group8/namepending.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


